config/routes.rb
Trainingsdiary::Application.routes.draw do

  devise_for :users

  get '/courses/download'                   , :controller => 'courses', :action => 'download'
  get '/courses/bigmap'                     , :controller => 'courses', :action => 'bigmap'
  get '/courses/draw'                       , :controller => 'courses', :action => 'draw'
  get '/courses/route_from_training'        , :to => 'courses#route_from_training'
  get '/courses/save_route_from_training'   , :to => 'courses#save_route_from_training'
  get '/trainings/bigcalendar'              , :to => 'trainings#bigcalendar'
  get '/trainings/newsimple'                , :to => 'trainings#newsimple'
  get '/listen' => 'pages#listen'
  get '/trainings/newsimple', :controller => 'trainings', :action => 'newsimple'
  get '/trainings/testxml', :controller => 'trainings', :action => 'testxml'
  get '/trainings/getWorkoutByStartTime', :controller => 'trainings', :action => 'getWorkoutByStartTime'
  post '/trainings/saveWorkouts', :controller => 'trainings', :action => 'saveWorkouts'
  post 'trainings/new'
  resources :courses

  
  resources :roles
  resources :pages
  resources :course_names
  resources :sports
  resources :sport_levels
  resources :trainings
  resources :statistics
  resources :blog_entries
  resources :workouts
  resources :tracks, :controller => 'tracks'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  
  resources :user, :controller => 'user'
   
  resources :sport_levels do
    post :sort, :on => :collection
  end
  resources :sports do
    post :sort, :on => :collection
  end
  resources :course_names do
    post :sort, :on => :collection
  end
  resources :trainings do
    post :save_workouts, :on => :collection
    post :sort, :on => :collection

  end

  get 'bigmap', :to => 'pages#bigmap'

=begin
	devise_for :users, :controllers => {:users => 'users'}  
		resources :user
	devise_scope :users do
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
	end
=end	
  root :to => 'pages#index'

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :trainings
  has_many :downloads
  belongs_to :user
  default_scope { order('sort_order') }
  scope :unorder,  -> { order('sort_order DESC') }

  def self.get_sports_by_mnemonic(mnemonic)
    return Sport.where('mnemonic = ?', mnemonic).first
  end

  def self.get_sports_by_user (user_id)
      return Sport.select('id, name').where('sports.user_id = ?',user_id)
  end

  def self.get_sport_type_by_id(id)
    sport = Sport.find(id)
    if sport.mnemonic == 'Biking'
      return 'BICYCLING'
    end
    if sport.mnemonic == 'Running'
      return 'WALKING'
    end
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    # GET /sports
    # GET /sports.xml
    before_filter :authenticate_user!, :except => [:sort]
    def index
        @sports = Sport.find(
                :all,                 
                :conditions => {:user_id => current_user.id }
                )
        #@log = Logger.new('log/sport.log')
        #@sports = Sport.with_exclusive_scope { find(:all) }
        #@log.debug(@sports)
        respond_to do |format|
            format.html # index.html.erb
            format.xml  { render :xml => @sports }
        end
    end
    
    # GET /sports/1
    # GET /sports/1.xml
    def show
        @sport = Sport.find(:first, :conditions => {:user_id => current_user.id, :id => params[:id]})
        
        respond_to do |format|
            format.html # show.html.erb
            format.xml  { render :xml => @sport }
        end
    end
    
    # GET /sports/new
    # GET /sports/new.xml
    def new
        @sport = Sport.new
        
        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @sport }
        end
    end
    
    # GET /sports/1/edit
    def edit
        @sport = Sport.find(:first,
                            :conditions => {:user_id => current_user.id , :id => params[:id]})
    end
    
    # POST /sports
    # POST /sports.xml
    def create
        #@sport = Sport.new(params[:sport])
        params[:sport][:user_id] = current_user.id
		    @sport = current_user.sports.new(params[:sport])
        respond_to do |format|
            if @sport.save
                format.html { redirect_to(sports_url, :notice => 'Sport was successfully created.') }
                format.xml  { render :xml => @sport, :status => :created, :location => @sport }
                format.js
                else
                format.html { render :action => "new" }
                format.xml  { render :xml => @sport.errors, :status => :unprocessable_entity }
                format.js
            end
        end
    end
    
    # PUT /sports/1
    # PUT /sports/1.xml
    def update
        @sport = Sport.find(:first,
                            :conditions => {:user_id => current_user.id , :id => params[:id]})
        
        respond_to do |format|
            if @sport.update_attributes(params[:sport])
                format.html { redirect_to(sports_url, :notice => 'Sport was successfully updated.') }
                format.xml  { head :ok }
                else
                format.html { render :action => "edit" }
                format.xml  { render :xml => @sport.errors, :status => :unprocessable_entity }
            end
        end
    end
    
    # DELETE /sports/1
    # DELETE /sports/1.xml
    def destroy
        @sport = Sport.find(params[:id])
        @sport.destroy
        
        respond_to do |format|
            format.html { redirect_to(sports_url, :notice => 'Sport was successfully deleted.') }
            format.xml  { head :ok }
        end
    end
    
    def sort
      @sports = Sport.all
      @sports.each do |sport|
        sport.sort = params[:list].index(sport.id.to_s)
        sport.save
      end 
      render :nothing => true 
    end
end

app/views/sports/_form.html.haml
= form_for @sport do |f|
  -if @sport.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sport.errors.count, "error")} prohibited this sport from being saved:"
      %ul
        - @sport.errors.full_messages.each do |msg|
          %li= msg
  %fieldset.edit
    .group
      = f.label :name, t("activerecord.attributes.sport.name", :default => "Sport"), :class => :label
      = f.text_field :name, :class => 'text_field'
      = f.hidden_field :user_id, :value => current_user.id
    .group.navform.wat-cf
      %button.button{:type => "submit"}
        = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
        = t("web-app-theme.save", :default => "Save")
      %span.text_button_padding= t("web-app-theme.or", :default => "or")
      = link_to t("web-app-theme.cancel", :default => "Cancel"), sports_path, :class => "text_button_padding link_button"

app/views/sports/create.js.haml
/* Insert a notice between the last sport and the sport form */
$("#sport-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Replace the count of sports */
$("#sports_count").html("<%= pluralize(Sport.count, 'Sport') %>");

/* Add the new sport to the bottom of the sports list */
$("#sports").append("<%= escape_javascript(render(@sport)) %>");

/* Highlight the new sport */
$("#sport_<%= @sport.id %>").effect("highlight", {}, 3000);

/* Reset the sport form */
$("#new_sport")[0].reset();

app/views/sports/edit.html.haml
.block
  .content
    %h2.title
      = t("sports")
      = t("web-app-theme.edit", :default => "Edit")

    .inner
      = form_for :sport, :url => sport_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/sports/index.html.haml
:javascript
  jQuery(document).ready(function(){
    jQuery('#sortable').sortable({
      axis: 'y',
      dropOnEmpty: false,       
      cursor: 'crosshair',
      items: 'li',
      opacity: 0.4,
      scroll: true,
      update: function(){
        jQuery.ajax({
          type: 'post',
          data: $('#sortable').sortable('serialize'),
          dataType: 'script',
          complete: function(request){
            jQuery('#sortable li').effect('highlight', {}, 2000);
          },
          url: '/sports/sort'
        })
      }
    });
  });
.block
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All Sports")
      = t("sports")
    .inner
      %ul#sortable
        - @sports.each do |sport|
          %li{:class => 'sortlist', :id => "list_#{sport.id.to_s}"}
            %table
              %tr
                %td{:class => "name"}
                  = sport.name
                %td{:class => "last"}
                  - if can? :update, @sports 
                    = link_to "Edit", edit_sport_path(@sports) 
                  |
                  \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_sport_path(sport)} |
                  \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", sport_path(sport), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf

app/views/sports/new.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      = t("sports")
    .inner
      = form_for :sport, :url => sports_path, :html => { :class => :form, :remote => true } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/sports/show.html.haml
.block
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.sport.name", :default => t("activerecord.labels.name", :default => "Name"))
          \:
        = @sport.name
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_sport_path(@sport), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), sport_path(@sport), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"