config/routes.rb
Trainingsdiary::Application.routes.draw do

  devise_for :users

  get '/courses/download'                   , :controller => 'courses', :action => 'download'
  get '/courses/bigmap'                     , :controller => 'courses', :action => 'bigmap'
  get '/courses/draw'                       , :controller => 'courses', :action => 'draw'
  get '/courses/route_from_training'        , :to => 'courses#route_from_training'
  get '/courses/save_route_from_training'   , :to => 'courses#save_route_from_training'
  get '/trainings/bigcalendar'              , :to => 'trainings#bigcalendar'
  get '/trainings/newsimple'                , :to => 'trainings#newsimple'
  get '/listen' => 'pages#listen'
  get '/trainings/newsimple', :controller => 'trainings', :action => 'newsimple'
  get '/trainings/testxml', :controller => 'trainings', :action => 'testxml'
  get '/trainings/getWorkoutByStartTime', :controller => 'trainings', :action => 'getWorkoutByStartTime'
  post '/trainings/saveWorkouts', :controller => 'trainings', :action => 'saveWorkouts'
  post 'trainings/new'
  resources :courses

  
  resources :roles
  resources :pages
  resources :course_names
  resources :sports
  resources :sport_levels
  resources :trainings
  resources :statistics
  resources :blog_entries
  resources :workouts
  resources :tracks, :controller => 'tracks'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  
  resources :user, :controller => 'user'
   
  resources :sport_levels do
    post :sort, :on => :collection
  end
  resources :sports do
    post :sort, :on => :collection
  end
  resources :course_names do
    post :sort, :on => :collection
  end
  resources :trainings do
    post :save_workouts, :on => :collection
    post :sort, :on => :collection

  end

  get 'bigmap', :to => 'pages#bigmap'

=begin
	devise_for :users, :controllers => {:users => 'users'}  
		resources :user
	devise_scope :users do
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
	end
=end	
  root :to => 'pages#index'

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
	#layout "standard", :except => [:ajax_method, :more_ajax, :another_ajax]
  # GET /blog_entries
  # GET /blog_entries.xml

  def index
		@blog_entries = BlogEntry.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blog_entries }
    end
  end

  def sort

      render :nothing => true
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.xml
  def show
    @blog_entry = BlogEntry.find(params[:id])
      respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blog_entry }
    end
  end

  # GET /blog_entries/new
  # GET /blog_entries/new.xml
  def new
    @blog_entry = BlogEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog_entry }
    end
  end

  # GET /blog_entries/1/edit
  def edit
    @blog_entry = BlogEntry.find(params[:id])
  end

  # POST /blog_entries
  # POST /blog_entries.xml
  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to(@blog_entry, :notice => 'Blog entry was successfully created.') }
        format.xml  { render :xml => @blog_entry, :status => :created, :location => @blog_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_entries/1
  # PUT /blog_entries/1.xml
  def update
    @blog_entry = BlogEntry.find(params[:id])
    respond_to do |format|
      if @blog_entry.update_attributes(params[:blog_entry])
        format.html { redirect_to(@blog_entry, :notice => 'Blog entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.xml
  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy

    respond_to do |format|
      format.html { redirect_to(blog_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/blog_entries/_form.html.haml
= form_for(BlogEntry.new) do |f|
      -#= f.hidden_field :id
      = f.label :comment
      %br/
      = f.text_area :subject, :rows => 2
      %br/
      %button.button{:type => 'button', :onclick=> 'postFile("<?xml version= ?>", "test");', :id=>'test'}
      = f.submit "Post Comment"

app/views/blog_entries/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_blog_entry_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      BlogEntry
    .inner
      = render :partial => "form"

app/views/blog_entries/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      BlogEntries
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.blog_entry.subject", :default => t("activerecord.labels.subject", :default => "Subject"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @blog_entries.each do |blog_entry|
          %tr{:class => cycle("odd", "even")}
            %td
              = blog_entry.id
            %td
              = link_to blog_entry.subject, blog_entry_path(blog_entry)
            %td
              = blog_entry.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", blog_entry_path(blog_entry)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_blog_entry_path(blog_entry)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", blog_entry_path(blog_entry), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions

app/views/blog_entries/new.html.haml
= javascript_include_tag 'prototype' ,
                         'garmin/connector'
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      BlogEntry
    .inner
      = render :partial => "form"

app/views/blog_entries/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", blog_entry_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.blog_entry.subject", :default => t("activerecord.labels.subject", :default => "Subject"))
          \:
        = @blog_entry.subject
      %p
        %b
          = t("activerecord.attributes.blog_entry.content", :default => t("activerecord.labels.content", :default => "Content"))
          \:
        = @blog_entry.content
      %p
        %b
          = t("activerecord.attributes.blog_entry.publish_at", :default => t("activerecord.labels.publish_at", :default => "Publish at"))
          \:
        = @blog_entry.publish_at
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_blog_entry_path(@blog_entry), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), blog_entry_path(@blog_entry), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"