config/routes.rb
Trainingsdiary::Application.routes.draw do

  devise_for :users

  get '/courses/download'                   , :controller => 'courses', :action => 'download'
  get '/courses/bigmap'                     , :controller => 'courses', :action => 'bigmap'
  get '/courses/draw'                       , :controller => 'courses', :action => 'draw'
  get '/courses/route_from_training'        , :to => 'courses#route_from_training'
  get '/courses/save_route_from_training'   , :to => 'courses#save_route_from_training'
  get '/trainings/bigcalendar'              , :to => 'trainings#bigcalendar'
  get '/trainings/newsimple'                , :to => 'trainings#newsimple'
  get '/listen' => 'pages#listen'
  get '/trainings/newsimple', :controller => 'trainings', :action => 'newsimple'
  get '/trainings/testxml', :controller => 'trainings', :action => 'testxml'
  get '/trainings/getWorkoutByStartTime', :controller => 'trainings', :action => 'getWorkoutByStartTime'
  post '/trainings/saveWorkouts', :controller => 'trainings', :action => 'saveWorkouts'
  post 'trainings/new'
  resources :courses

  
  resources :roles
  resources :pages
  resources :course_names
  resources :sports
  resources :sport_levels
  resources :trainings
  resources :statistics
  resources :blog_entries
  resources :workouts
  resources :tracks, :controller => 'tracks'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  
  resources :user, :controller => 'user'
   
  resources :sport_levels do
    post :sort, :on => :collection
  end
  resources :sports do
    post :sort, :on => :collection
  end
  resources :course_names do
    post :sort, :on => :collection
  end
  resources :trainings do
    post :save_workouts, :on => :collection
    post :sort, :on => :collection

  end

  get 'bigmap', :to => 'pages#bigmap'

=begin
	devise_for :users, :controllers => {:users => 'users'}  
		resources :user
	devise_scope :users do
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
	end
=end	
  root :to => 'pages#index'

end

app/models/course_name.rb
class CourseName < ActiveRecord::Base
	has_many :trainings
	belongs_to :user
  default_scope { order('sort') }
  validates :name, :presence => true
  
  def self.get_coursename_by_user (user_id)
      return CourseName.select('id, name').where('user_id = ?', user_id).all
  end
  def self.get_last_coursename_by_user (user_id)
    return CourseName.select('id, name').where('user_id = ?', user_id).order('sort DESC').first
  end
end

app/controllers/course_names_controller.rb
class CourseNamesController < ApplicationController
    # GET /course_names
    # GET /course_names.xml
    before_filter :authenticate_user!, :except => [:sort]
    #load_and_authorize_resource
    def index
      @course_names = CourseName.where(['course_names.user_id= ?', current_user])

        #@course_names = course_names.paginate:page => params[:page], :per_page => 25
        respond_to do |format|
            format.html # index.html.erb
            format.xml  { render :xml => @course_names }
        end
    end

    # GET /course_names/1
    # GET /course_names/1.xml
    def show
        @course_name = CourseName.where(
            :conditions => {:user_id => current_user.id ,
                            :id => params[:id]}

        ).limit(1)
        respond_to do |format|
            format.html # show.html.erb
            format.xml  { render :xml => @course_name }
        end
    end

    # GET /course_names/new
    # GET /course_names/new.xml
    def new
        @course_name = CourseName.new
        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @course_name }
        end
    end

    # GET /course_names/1/edit
    def edit
      @course_name = CourseName.where('course_names.user_id = ? AND course_names.id = ?', current_user, params[:id]).first
    end

    # POST /course_names
    # POST /course_names.xml
    def create
        params[:course_name][:user_id] = current_user.id
        @course_name = CourseName.new(course_params)

        respond_to do |format|
            if @course_name.save
                format.html { redirect_to(course_names_url, :notice => 'Course name was successfully created.') }
                format.xml  { render :xml => @course_name, :status => :created, :location => @course_name }
            else
                format.html { render :action => "new" }
                format.xml  { render :xml => @course_name.errors, :status => :unprocessable_entity }
            end
        end
    end

    # PUT /course_names/1
    # PUT /course_names/1.xml
    def update
        params[:course_name][:user_id] = current_user.id
        @course_name = CourseName.find(params[:id])

        respond_to do |format|
            if @course_name.update_attributes(course_params)
                format.html { redirect_to(course_names_url, :notice => 'Course name was successfully updated.') }
                format.xml  { head :ok }
            else
                format.html { render :action => "edit" }
                format.xml  { render :xml => @course_name.errors, :status => :unprocessable_entity }
            end
        end
    end

    # DELETE /course_names/1
    # DELETE /course_names/1.xml
    def destroy
        @course_name = CourseName.find(params[:id])
        @course_name.destroy

        respond_to do |format|
            format.html { redirect_to(course_names_url) }
            format.xml  { head :ok }
        end
    end
    
    def sort
      @course_names = CourseName.all
      @course_names.each do |course_name|
        course_name.sort = params[:list].index(course_name.id.to_s)
        course_name.save
      end 
      render :nothing => true 
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course_name).permit(:course_name, :name, :user_id)
    end
end

app/views/course_names/_form.html.haml
= form_for @course_name, :html => { :class => 'form' } do |f|
  -if @course_name.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course_name.errors.count, "error")} prohibited this course name from being saved:"
      %ul
        - @course_name.errors.full_messages.each do |msg|
          %li= msg
  %fieldset.edit
    .group
      = f.label :name, t("course names"), :class => :label
      = f.text_field :name, :class => 'text_field'
      = f.hidden_field :user_id, :value => current_user.id
    .group.navform.wat-cf
      %button.button{:type => "submit"}
        = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
        = t("web-app-theme.save", :default => "Save")
      %span.text_button_padding= t("web-app-theme.or", :default => "or")
      = link_to t("web-app-theme.cancel", :default => "Cancel"), course_names_path, :class => "text_button_padding link_button"

app/views/course_names/edit.html.haml
.detail
  .content
    %h2.title
      = t("course name")
      = t("web-app-theme.edit", :default => "Edit")
    .inner
      = form_for :course_name, :url => course_name_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/course_names/index.html.haml
:javascript
  jQuery(document).ready(function(){
    jQuery('#sortable').sortable({
      axis: 'y',
      dropOnEmpty: false,       
      cursor: 'crosshair',
      items: 'li',
      opacity: 0.4,
      scroll: true,
      update: function(){
        jQuery.ajax({
          type: 'post',
          data: jQuery('#sortable').sortable('serialize'),
          dataType: 'script',
          complete: function(request){
            jQuery('#sortable li').effect('highlight', {}, 2000);
          },
          url: '/course_names/sort'
        })
      }
    });
  });
.block
  .content
    .inner
      %ul#sortable
        - @course_names.each do |course_name|
          %li{:class => 'sortlist', :id => "list_#{course_name.id.to_s}"}
            %table            
              %tr{:class => cycle("odd", "even")}
                %td{:class => "name"}
                  = course_name.name
                %td.last
                  = link_to "#{t('web-app-theme.edit', :default => 'Edit')}", edit_course_name_path(course_name)
                  = link_to "#{t('web-app-theme.delete', :default => 'Delete')}", course_name_path(course_name), :method => :delete, :data => { :confirm => "#{t('web-app-theme.confirm', :default => 'Are you sure?')}" }

app/views/course_names/new.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      = t("course names")
    .inner
      = render :partial => 'form'

app/views/course_names/show.html.haml
.block
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.course_name.name", :default => t("activerecord.labels.name", :default => "Name"))
          \:
        = @course_name.name

      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_course_name_path(@course_name), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), course_name_path(@course_name), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"