config/routes.rb
Trainingsdiary::Application.routes.draw do

  devise_for :users

  get '/courses/download'                   , :controller => 'courses', :action => 'download'
  get '/courses/bigmap'                     , :controller => 'courses', :action => 'bigmap'
  get '/courses/draw'                       , :controller => 'courses', :action => 'draw'
  get '/courses/route_from_training'        , :to => 'courses#route_from_training'
  get '/courses/save_route_from_training'   , :to => 'courses#save_route_from_training'
  get '/trainings/bigcalendar'              , :to => 'trainings#bigcalendar'
  get '/trainings/newsimple'                , :to => 'trainings#newsimple'
  get '/listen' => 'pages#listen'
  get '/trainings/newsimple', :controller => 'trainings', :action => 'newsimple'
  get '/trainings/testxml', :controller => 'trainings', :action => 'testxml'
  get '/trainings/getWorkoutByStartTime', :controller => 'trainings', :action => 'getWorkoutByStartTime'
  post '/trainings/saveWorkouts', :controller => 'trainings', :action => 'saveWorkouts'
  post 'trainings/new'
  resources :courses

  
  resources :roles
  resources :pages
  resources :course_names
  resources :sports
  resources :sport_levels
  resources :trainings
  resources :statistics
  resources :blog_entries
  resources :workouts
  resources :tracks, :controller => 'tracks'

  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  
  resources :user, :controller => 'user'
   
  resources :sport_levels do
    post :sort, :on => :collection
  end
  resources :sports do
    post :sort, :on => :collection
  end
  resources :course_names do
    post :sort, :on => :collection
  end
  resources :trainings do
    post :save_workouts, :on => :collection
    post :sort, :on => :collection

  end

  get 'bigmap', :to => 'pages#bigmap'

=begin
	devise_for :users, :controllers => {:users => 'users'}  
		resources :user
	devise_scope :users do
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
	end
=end	
  root :to => 'pages#index'

end

app/controllers/courses_controller.rb
require 'rexml/document'

require 'json'
load "fileutils.rb"
class CoursesController < ApplicationController
  #@log = Logger.new('log/courses.log')
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :init
  load_and_authorize_resource
  #include Trainingsdata
  
  def init
    @log          = Logger.new('log/courses.log')  
    @course_path  = Rails.root + 'public/uploads/course/file/' + current_user.id.to_s
    @name         = 'Trainingsdiary'
  end
  
  # GET /courses
  # GET /courses.xml
  def index
    @courses = Course.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end
  
  def download
    filename  = params[:filename]
    send_file @course_path.to_s + '/' + params[:id].to_s + '/' + filename.to_s, :type=>"application/text"
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    
    @course = Course.find(params[:id])    
    file = @course_path.to_s + '/' + params[:id].to_s + '/' +  @course.file.to_s    
    
    td = Trainingsdata::Forerunner.new(file)   
    td.generate_course
    @route = td.course.to_s
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new
    @sport = Sport.find(
      :all,
      :select => 'id, name',
      :conditions => {:user_id => current_user.id}
    )
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @sport = Sport.find(
      :all,
      :select => 'id, name',
      :conditions => {:user_id => current_user.id}
    )
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    
    Course.mounting

    @sport = Sport.find(
      :all,
      :select => 'id, name',
      :conditions => {:user_id => current_user.id}
    )
    
    @course = Course.new(params[:course])
    @course.user = current_user
    respond_to do |format|
       
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    Course.mounting
     
    @course = Course.find(params[:id])
    @course.user = current_user
    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    @file = @course_path.to_s + '/' + params[:id].to_s + '/' +  @course.file.to_s
    @filetree = @course_path.to_s + '/' + params[:id].to_s
    self.cleanup
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end
  
  def create_file_from_activity(id)
    @training.map_data = @training.map_data.squeeze("]]")
    @training.map_data.slice!(0..2)
    degrees = 0
    @deg = Array.new
    
    degrees = @training.map_data.split('],[')
    degrees.each do |item| 
      item = item.gsub(/[\[\]]/,'') 
      pair = item.split(',')
      if (pair.count() == 2)
        @deg << pair
      end
    end
    Dir.mkdir(@course_path.to_s + '/' + id.to_s) 
    path  = @course_path.to_s + '/' + id.to_s + '/' + @course.name
    td    = Trainingsdata::Forerunner.new(path, true)
    td.create_trainings_file(@deg, @training, @name)

  end
  
  def save_route_from_training
    @course       = Course.new(params[:course])
    @name         = params[:course][:name]
    @course.user  = current_user
    @training     = Training.find(:first,
                                  :select => 'trainings.map_data, trainings.time_total,trainings.start_time, trainings.distance_total',
                                  :conditions => ['trainings.user_id = ? AND trainings.id = ?', current_user , params[:course][:trainings_id].to_i]
                                )
    @training.distance_total  = params[:course][:distance]                           
    @course.file              = @name + '.tcx'
    if @course.save      
      self.create_file_from_activity(@course.id)
      flash[:notice] = "course created"
      redirect_to "/courses" 
    else
      flash[:notice] = "course not created"
      redirect_to "/courses" 
    end
  end
  
  def route_from_training
    @course = Course.new
    @sport  = Sport.get_sports_by_user(current_user.id)
     
    @training = Training.find(:first,
                :select => 'trainings.start_time, trainings.id, trainings.map_data, trainings.distance_total, trainings.time_total, trainings.sport_id, trainings.course_name_id',
                :conditions => ['trainings.user_id = ? AND trainings.id = ?', current_user , params[:trainings_id]],
                :joins => [:sport, :course_name]
              )
              
    respond_to do |format|
      format.html # create_fro_activity.html.erb
      format.xml  { render :xml => @course }
    end
    
  end
  
  def cleanup
    File.delete(@file) if File.exist?(@file)
    begin
      FileUtils.remove_dir(@filetree)
    rescue
    end
    
  end
  
  def bigmap
    id        = params[:id]
    @course   = Course.find(id)
    file      = @course_path.to_s + '/' + params[:id].to_s + '/' +  @course.file.to_s   
    td        = Trainingsdata::Forerunner.new(file)
    td.generate_course
    @course   = td.course.to_s                    
    render :partial => 'bigmap.html.haml'
  end
end

app/views/courses/_bigmap.html.haml
= javascript_include_tag 'jquery', 'jquery-ui.min', 'rails', 'application','OpenLayers', 'OpenStreetMap'
%script{:type => "text/javascript", :src  => "http://maps.google.com/maps/api/js?v=3.5&sensor=false"}
#map
  
:javascript
  createMapWithRoute( #{@course}, "map");
  
           

app/views/courses/_form.html.haml
%ul#coursesform
  = form_for @course do |f|
    -if @course.errors.any?
      #error_explanation
        %h3
          = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
        %ul
          - @course.errors.full_messages.each do |msg|
            %li= msg

    %li
      = f.label :sport_id, t("activerecord.attributes.course.sport_id", :default => "Sport"), :class => :label
      - @sport.each do |option| 
        %label
          .radio
            = f.radio_button :sport_id, option.id
          = t("activerecord.attributes.course.sport", :default => option.name)
    %li
      = f.label :name, t("activerecord.attributes.course.name", :default => "Name"), :class => :label
      = f.text_field :name , :class => 'text_field' 
    %li
      = f.label :file, t("activerecord.attributes.course.file", :default => "File"), :class => :label
      = f.file_field :file, :class => 'file_field'
       
    %li
      = f.label :comment
      = f.text_area :comment, :class => 'text_area', :cols => 20

    .group.navform.wat-cf
      %button.button{:type => "submit"}
        = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
        = t("web-app-theme.save", :default => "Save")

app/views/courses/create_from_activity.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")

    .inner
      = form_for :course, :html => { :id => 'course', :class => :form, :multipart => true} do |f|
        %ul#coursesform
          %li
            = f.label :created_at
            = f.text_field :name , :class => 'text_field' 
          %li
            = f.file_field :file, :class => 'file_field'

          %li
            = f.text_area :comment, :class => 'text_area', :cols => 20

          .group.navform.wat-cf
            %button.button{:type => "submit"}
              = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
              = t("web-app-theme.save", :default => "Save")

app/views/courses/edit.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      = @course.file
    .inner
      = form_for :course, :url => course_path, :html => { :id => 'course', :class => :form, :multipart => true} do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/courses/index.html.haml
.block
  .content
    .inner
      %ul#sortable
        - @courses.each do |course|
          %h3
            = course.sport.name    
          %li{:class => 'sortlist', :id => "list_#{course.id.to_s}"}
            %table
              %tr
                %td{:class => "name"}
                  = course.name
                  = link_to t("Download"), :controller => "courses", :action =>"download", :id=>course.id.to_s, :filename => course.file.to_s
                %td{:class => "last"}
                  \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_course_path(course)} |
                  \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", course_path(course), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf

app/views/courses/new.html.haml
.block
  .content
    %h2.title
      = t("web-app-theme.new_course", :default => "New Download")
    .inner
      = form_for :course, :url => courses_path, :html => { :id => 'course', :class => :form, :multipart => true } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/courses/route_from_training.html.haml
.block
  .content
    %h2.title
      = t("create trainings route", :default => "create trainings route")
      = @course.file
    .inner
     
      = form_for @course, :url => { :action => "save_route_from_training" },:html => { :id => 'course', :class => :form }, :method => "post" do |f|
        -if @course.errors.any?
          #error_explanation
            %h3
              = t('activerecord.errors.template.header', :model => Training.model_name.human, :count => @training.errors.count)
            %ul
              - @training.errors.full_messages.each do |msg|
                %li= msg
        %ul#coursesform
          %li
            = f.label :sport_id, t("activerecord.attributes.course.sport_id", :default => "Sport"), :class => :label
            - @sport.each do |option| 
              %label
                .radio
                  = f.radio_button :sport_id, option.id
                = t("activerecord.attributes.course.sport", :default => option.name)
          %li
            = f.label :name, t("activerecord.attributes.course.name", :default => "Name"), :class => :label
            = f.text_field :name , :class => 'text_field required' , :value => @training.course_name.name.to_s
          %li
            = f.label :distance, t("activerecord.attributes.course.distance", :default => "Distance"), :class => :label
            = f.text_field :distance, :class => 'text_field', :value => @training.distance_total.to_i
          %li
            = f.label :comment
            = f.text_area :comment, :class => 'text_area', :cols => 40

          = f.hidden_field :trainings_id, :class => 'text_field', :value => @training.id

          .group.navform.wat-cf
            %button.button{:type => "submit"}
              = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
              = t("web-app-theme.save", :default => "Save")

app/views/courses/show.html.haml
= javascript_include_tag 'OpenLayers', 'OpenStreetMap'
.block
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.course.name", :default => t("activerecord.labels.course", :default => "Name"))
          \:
        = @course.name
      %p
        %b
          = t("activerecord.attributes.course.comment", :default => t("activerecord.labels.course", :default => "Comment"))
          \:
        = @course.comment
      %p
        %b
          = t("activerecord.attributes.course.file", :default => t("activerecord.labels.file", :default => "File"))
          \:
        = @course.file 
        .link_big_map
          = link_to t('fullscreen', :default =>'show fullscreen'), { :controller=>"courses", :action=>"bigmap", :id => "#{@course.id}" }, :id => 'bigmap', :class => 'iframe'
        #map
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_course_path(@course), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), sport_path(@course), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
:javascript
  createMapWithRoute( #{@route}, "map");